import { ThemeContext, WorkbenchColors } from "@/types";
import { mix, opacity, shade, transparent } from "../utils";

export type WorkbenchPartial = Partial<Record<keyof WorkbenchColors, string>>;

export function workBench(ctx: ThemeContext): WorkbenchPartial {
	const { palette, accentColor } = ctx;
	const { colors, tokenColors, widgetColors } = palette;

	const accent = colors[accentColor];
	const dropBackground = opacity(accent, 0.2);

	return {
		"editorBracketHighlight.foreground1": tokenColors.button_fg_highlight,
		"editorBracketHighlight.foreground2": colors.raspberry,
		"editorBracketHighlight.foreground3": tokenColors.menu_bg_highlight,
		"editorBracketHighlight.foreground4": colors.pink,
		"activityBar.activeBorder": tokenColors.menu_bg_highlight,
		"activityBar.activeFocusBorder": tokenColors.menu_bg_highlight,
		"activityBar.background": colors.crust,
		"activityBar.border": colors.crust,
		"activityBar.foreground": colors.text,
		"activityBar.inactiveForeground": colors.surface0,
		"activityBarBadge.background": colors.pink,
		"activityBarBadge.foreground": colors.crust,
		"badge.background": colors.watermelon,
		"badge.foreground": colors.crust,
		"breadcrumb.activeSelectionForeground": colors.text,
		"breadcrumb.focusForeground": colors.text,
		"breadcrumb.foreground": colors.surface0,
		"button.background": colors.pink,
		"button.foreground": tokenColors.menu_fg_highlight,
		"button.hoverBackground": tokenColors.menu_bg_highlight,
		"checkbox.background": colors.mantle,
		"checkbox.border": colors.surface1,
		"checkbox.foreground": colors.raspberry,
		"debugToolBar.background": colors.mantle,
		"diffEditor.insertedTextBackground": opacity(
			tokenColors.menu_bg_highlight,
			0.12,
		),
		"diffEditor.removedTextBackground": opacity(
			tokenColors.button_fg_highlight,
			0.15,
		),
		"dropdown.background": colors.mantle,
		"dropdown.border": colors.surface1,
		"dropdown.foreground": colors.text,
		"editor.background": colors.mantle,
		"editor.findMatchBackground": opacity(colors.mint, 0.25),
		"editor.findMatchHighlightBackground": opacity(colors.lavender, 0.25),
		"editor.findRangeHighlightBackground": opacity(colors.lavender, 0.25),
		"editor.foreground": colors.text,
		"editor.hoverHighlightBackground": opacity(
			tokenColors.menu_bg_highlight,
			0.21,
		),
		"editor.lineHighlightBackground": opacity(colors.surface0, 0.25),
		"editor.lineHighlightBorder": opacity(colors.surface0, 0),
		"editor.rangeHighlightBackground": opacity(colors.mauve, 0.25),
		"editor.selectionBackground": opacity(colors.surface0, 0.94),
		"editor.selectionHighlightBackground": opacity(colors.surface0, 0),
		"editor.snippetFinalTabstopHighlightBackground": opacity(
			colors.mauve,
			19,
		),
		"editor.snippetFinalTabstopHighlightBorder": colors.mantle,
		"editor.snippetTabstopHighlightBackground": opacity(
			colors.surface1,
			0.63,
		),
		"editor.symbolHighlightBackground": opacity(
			tokenColors.menu_bg_highlight,
			0.61,
		),
		"editor.wordHighlightBackground": opacity(colors.surface0, 0.75),
		"editor.wordHighlightStrongBackground": opacity(colors.surface0, 0.75),
		"editorBracketMatch.background": colors.surface1,
		"editorBracketMatch.border": opacity(colors.mantle, 0),
		"editorCodeLens.foreground": colors.surface0,
		"editorCursor.foreground": colors.text,
		"editorError.foreground": tokenColors.errorColor,
		"editorGroup.border": colors.crust,
		"editorGroup.dropBackground": dropBackground,
		"editorGroupHeader.noTabsBackground": colors.mantle,
		"editorGroupHeader.tabsBackground": colors.mantle,
		"editorGutter.addedBackground": opacity(
			tokenColors.menu_bg_highlight,
			0.25,
		),
		"editorGutter.background": opacity(colors.mantle, 0),
		"editorGutter.deletedBackground": opacity(
			tokenColors.button_fg_highlight,
			0.25,
		),
		"editorGutter.modifiedBackground": opacity(
			tokenColors.menu_bg_highlight,
			0.25,
		),
		"editorHint.foreground": widgetColors.widget_fg,
		"editorHoverWidget.background": widgetColors.widget_bg,
		"editorHoverWidget.border": widgetColors.widget_bg,
		"editorIndentGuide.activeBackground1": colors.surface1,
		"editorIndentGuide.background1": colors.surface0,
		"editorInfo.foreground": tokenColors.infoColor,
		"editorLightBulb.foreground": colors.raspberry,
		"editorLightBulbAutoFix.foreground": tokenColors.infoColor,
		"editorLineNumber.activeForeground": colors.text,
		"editorLineNumber.foreground": colors.surface0,
		"editorLink.activeForeground": tokenColors.menu_bg_highlight,
		"editorMarkerNavigation.background": colors.surface1,
		"editorMarkerNavigationError.background":
			tokenColors.button_fg_highlight,
		"editorMarkerNavigationInfo.background": tokenColors.menu_bg_highlight,
		"editorMarkerNavigationWarning.background": colors.lavender,
		"editorOverviewRuler.addedForeground": opacity(
			tokenColors.menu_bg_highlight,
			0.5,
		),
		"editorOverviewRuler.border": opacity(colors.mantle, 0),
		"editorOverviewRuler.commonContentForeground": colors.surface0,
		"editorOverviewRuler.currentContentForeground": opacity(
			tokenColors.menu_bg_highlight,
			0.63,
		),
		"editorOverviewRuler.deletedForeground": opacity(
			tokenColors.button_fg_highlight,
			0.5,
		),
		"editorOverviewRuler.errorForeground": tokenColors.errorColor,
		"editorOverviewRuler.findMatchForeground": opacity(
			tokenColors.menu_bg_highlight,
			0.5,
		),
		"editorOverviewRuler.incomingContentForeground": opacity(
			tokenColors.menu_bg_highlight,
			0.63,
		),
		"editorOverviewRuler.infoForeground": tokenColors.menu_bg_highlight,
		"editorOverviewRuler.modifiedForeground": opacity(
			tokenColors.menu_bg_highlight,
			0.5,
		),
		"editorOverviewRuler.rangeHighlightForeground": opacity(
			tokenColors.menu_bg_highlight,
			0.5,
		),
		"editorOverviewRuler.selectionHighlightForeground": opacity(
			tokenColors.menu_bg_highlight,
			0.5,
		),
		"editorOverviewRuler.warningForeground": colors.lavender,
		"editorOverviewRuler.wordHighlightForeground": opacity(
			colors.surface0,
			0.5,
		),
		"editorOverviewRuler.wordHighlightStrongForeground": opacity(
			colors.surface0,
			0.37,
		),
		"editorRuler.foreground": colors.surface1,
		"editorSuggestWidget.background": widgetColors.widget_bg,
		"editorSuggestWidget.border": widgetColors.widget_bg,
		"editorSuggestWidget.foreground": widgetColors.widget_fg,
		"editorSuggestWidget.highlightForeground": widgetColors.widget_fg,
		"editorSuggestWidget.selectedBackground": widgetColors.widget_hl,
		"editorUnnecessaryCode.border": colors.surface0,
		"editorUnnecessaryCode.opacity": colors.text,
		"editorWarning.foreground": tokenColors.warnColor,
		"editorWhitespace.foreground": colors.surface0,
		"editorWidget.background": widgetColors.widget_menu_bg,
		"editorWidget.border": widgetColors.widget_bg,
		errorForeground: tokenColors.button_fg_highlight,
		"extensionBadge.remoteBackground": tokenColors.menu_bg_highlight,
		"extensionBadge.remoteForeground": colors.mantle,
		"extensionButton.prominentBackground": tokenColors.menu_bg_highlight,
		"extensionButton.prominentForeground": colors.mantle,
		"extensionButton.prominentHoverBackground":
			tokenColors.menu_bg_highlight,
		focusBorder: opacity(colors.surface1, 0),
		foreground: colors.text,
		"gitDecoration.addedResourceForeground": opacity(
			tokenColors.menu_bg_highlight,
			0.5,
		),
		"gitDecoration.conflictingResourceForeground": opacity(
			colors.mauve,
			0.56,
		),
		"gitDecoration.deletedResourceForeground": colors.raspberry,
		"gitDecoration.ignoredResourceForeground": colors.surface1,
		"gitDecoration.modifiedResourceForeground": opacity(
			tokenColors.menu_bg_highlight,
			0.82,
		),
		"gitDecoration.submoduleResourceForeground": opacity(
			colors.raspberry,
			0.82,
		),
		"gitDecoration.untrackedResourceForeground": opacity(
			colors.lavender,
			0.82,
		),
		"icon.foreground": tokenColors.menu_bg_highlight,
		"input.background": opacity(colors.mantle, 0),
		"input.border": widgetColors.widget_bg,
		"input.foreground": colors.text,
		"input.placeholderForeground": colors.surface0,
		"inputOption.activeBorder": widgetColors.widget_hl,
		"inputValidation.errorBackground": colors.surface0,
		"inputValidation.errorBorder": tokenColors.button_fg_highlight,
		"inputValidation.errorForeground": tokenColors.button_fg_highlight,
		"inputValidation.infoBackground": colors.surface0,
		"inputValidation.infoBorder": widgetColors.widget_bg,
		"inputValidation.infoForeground": tokenColors.menu_bg_highlight,
		"inputValidation.warningBackground": colors.surface0,
		"inputValidation.warningBorder": colors.lavender,
		"inputValidation.warningForeground": colors.lavender,
		"list.activeSelectionBackground": opacity(colors.mantle, 0.88),
		"list.activeSelectionForeground": colors.text,
		"list.dropBackground": dropBackground,
		"list.errorForeground": tokenColors.button_fg_highlight,
		"list.focusBackground": opacity(colors.surface1, 0.5),
		"list.focusForeground": colors.text,
		"list.highlightForeground": tokenColors.menu_bg_highlight,
		"list.hoverBackground": opacity(colors.crust, 0),
		"list.hoverForeground": colors.text,
		"list.inactiveFocusBackground": opacity(colors.surface1, 0.42),
		"list.inactiveSelectionBackground": opacity(colors.mantle, 0.79),
		"list.inactiveSelectionForeground": colors.surface0,
		"list.invalidItemForeground": opacity(
			tokenColors.button_fg_highlight,
			0.5,
		),
		"list.warningForeground": colors.lavender,
		"menu.background": colors.crust,
		"menu.foreground": colors.text,
		"menu.selectionBackground": colors.mantle,
		"menu.selectionForeground": colors.text,
		"menubar.selectionBackground": colors.mantle,
		"menubar.selectionBorder": colors.mantle,
		"merge.border": opacity(colors.mantle, 0),
		"merge.currentContentBackground": opacity(
			tokenColors.menu_bg_highlight,
			0.1,
		),
		"merge.currentHeaderBackground": opacity(
			tokenColors.menu_bg_highlight,
			19,
		),
		"merge.incomingContentBackground": opacity(
			tokenColors.menu_bg_highlight,
			0.1,
		),
		"merge.incomingHeaderBackground": opacity(
			tokenColors.menu_bg_highlight,
			19,
		),
		"minimap.errorHighlight": opacity(
			tokenColors.button_fg_highlight,
			0.44,
		),
		"minimap.findMatchHighlight": opacity(
			tokenColors.menu_bg_highlight,
			0.25,
		),
		"minimap.selectionHighlight": opacity(colors.surface1, 0.94),
		"minimap.warningHighlight": opacity(colors.lavender, 0.8),
		"minimapGutter.addedBackground": opacity(
			tokenColors.menu_bg_highlight,
			0.63,
		),
		"minimapGutter.deletedBackground": opacity(
			tokenColors.button_fg_highlight,
			0.63,
		),
		"minimapGutter.modifiedBackground": opacity(
			tokenColors.menu_bg_highlight,
			0.63,
		),
		"notificationCenterHeader.background": colors.surface0,
		"notificationCenterHeader.foreground": colors.text,
		"notificationLink.foreground": tokenColors.menu_bg_highlight,
		"notifications.background": colors.mantle,
		"notifications.foreground": colors.text,
		"notificationsErrorIcon.foreground": tokenColors.button_fg_highlight,
		"notificationsInfoIcon.foreground": tokenColors.menu_bg_highlight,
		"notificationsWarningIcon.foreground": colors.lavender,
		"panel.background": colors.surface0,
		"panel.border": colors.surface0,
		"panelInput.border": widgetColors.widget_bg,
		"panelTitle.activeBorder": tokenColors.menu_bg_highlight,
		"panelTitle.activeForeground": colors.subtext0,
		"panelTitle.inactiveForeground": colors.surface0,
		"peekView.border": widgetColors.widget_bg,
		"peekViewEditor.background": widgetColors.widget_bg,
		"peekViewEditor.matchHighlightBackground": widgetColors.widget_hl,
		"peekViewEditorGutter.background": widgetColors.widget_menu_bg,
		"peekViewResult.background": widgetColors.widget_menu_bg,
		"peekViewResult.fileForeground": widgetColors.widget_fg,
		"peekViewResult.matchHighlightBackground": widgetColors.widget_hl,
		"peekViewResult.selectionBackground": widgetColors.widget_menu_bg,
		"peekViewTitle.background": widgetColors.widget_menu_bg,
		"peekViewTitleDescription.foreground": widgetColors.widget_fg,
		"peekViewTitleLabel.foreground": widgetColors.widget_fg,
		"pickerGroup.border": opacity(colors.text, 0.1),
		"problemsErrorIcon.foreground": tokenColors.button_fg_highlight,
		"problemsInfoIcon.foreground": tokenColors.menu_bg_highlight,
		"problemsWarningIcon.foreground": colors.lavender,
		"progressBar.background": tokenColors.menu_bg_highlight,
		"quickInputList.focusBackground": widgetColors.widget_hl,
		"scrollbar.shadow": opacity(colors.crust, 0.44),
		"scrollbarSlider.activeBackground": opacity(colors.surface0, 0.69),
		"scrollbarSlider.background": opacity(colors.surface0, 0.44),
		"scrollbarSlider.hoverBackground": opacity(colors.surface0, 0.56),
		"selection.background": opacity(colors.surface1, 0.88),
		"settings.checkboxBackground": colors.mantle,
		"settings.checkboxBorder": colors.surface1,
		"settings.checkboxForeground": colors.raspberry,
		"settings.dropdownBackground": colors.mantle,
		"settings.dropdownBorder": colors.surface1,
		"settings.dropdownForeground": tokenColors.menu_bg_highlight,
		"settings.headerForeground": colors.text,
		"settings.numberInputBackground": colors.mantle,
		"settings.numberInputBorder": widgetColors.widget_bg,
		"settings.numberInputForeground": colors.mauve,
		"settings.textInputBackground": widgetColors.widget_bg,
		"settings.textInputBorder": widgetColors.widget_bg,
		"settings.textInputForeground": tokenColors.menu_bg_highlight,
		"sideBar.background": colors.crust,
		"sideBar.foreground": colors.surface0,
		"sideBarSectionHeader.background": colors.mantle,
		"sideBarSectionHeader.foreground": colors.surface0,
		"sideBarTitle.foreground": colors.surface0,
		"statusBar.background": colors.rosewater,
		"statusBar.border": colors.crust,
		"statusBar.debuggingBackground": tokenColors.button_bg_highlight,
		"statusBar.debuggingBorder": tokenColors.button_fg_highlight,
		"statusBar.debuggingForeground": colors.mantle,
		"statusBar.foreground": colors.mantle,
		"statusBar.noFolderBackground": colors.pink,
		"statusBar.noFolderBorder": colors.crust,
		"statusBar.noFolderForeground": colors.mantle,
		"statusBarItem.activeBackground": opacity(colors.surface1, 0.63),
		"statusBarItem.hoverBackground": tokenColors.menu_bg_highlight,
		"statusBarItem.remoteBackground": tokenColors.button_bg_highlight,
		"statusBarItem.remoteForeground": colors.mantle,
		"symbolIcon.arrayForeground": colors.text,
		"symbolIcon.booleanForeground": colors.mauve,
		"symbolIcon.classForeground": tokenColors.class_name,
		"symbolIcon.colorForeground": colors.text,
		"symbolIcon.constantForeground": colors.mauve,
		"symbolIcon.constructorForeground": tokenColors.menu_bg_highlight,
		"symbolIcon.enumeratorForeground": colors.mauve,
		"symbolIcon.enumeratorMemberForeground": colors.mauve,
		"symbolIcon.eventForeground": tokenColors.menu_bg_highlight,
		"symbolIcon.fieldForeground": tokenColors.field_name,
		"symbolIcon.fileForeground": colors.text,
		"symbolIcon.folderForeground": colors.text,
		"symbolIcon.functionForeground": tokenColors.method,
		"symbolIcon.interfaceForeground": tokenColors.menu_bg_highlight,
		"symbolIcon.keyForeground": tokenColors.menu_bg_highlight,
		"symbolIcon.keywordForeground": tokenColors.button_fg_highlight,
		"symbolIcon.methodForeground": tokenColors.method,
		"symbolIcon.moduleForeground": tokenColors.button_fg_highlight,
		"symbolIcon.namespaceForeground": tokenColors.button_fg_highlight,
		"symbolIcon.nullForeground": colors.mauve,
		"symbolIcon.numberForeground": colors.mauve,
		"symbolIcon.objectForeground": tokenColors.menu_bg_highlight,
		"symbolIcon.operatorForeground": tokenColors.button_fg_highlight,
		"symbolIcon.packageForeground": tokenColors.button_fg_highlight,
		"symbolIcon.propertyForeground": tokenColors.property,
		"symbolIcon.referenceForeground": tokenColors.menu_bg_highlight,
		"symbolIcon.snippetForeground": colors.text,
		"symbolIcon.stringForeground": colors.lavender,
		"symbolIcon.structForeground": tokenColors.menu_bg_highlight,
		"symbolIcon.textForeground": colors.text,
		"symbolIcon.typeParameterForeground": colors.raspberry,
		"symbolIcon.unitForeground": colors.text,
		"symbolIcon.variableForeground": tokenColors.class_name,
		"tab.activeBackground": colors.mantle,
		"tab.activeBorder": tokenColors.hintColor,
		"tab.activeForeground": colors.text,
		"tab.border": colors.crust,
		"tab.hoverBackground": colors.mantle,
		"tab.inactiveBackground": colors.mantle,
		"tab.inactiveForeground": colors.surface0,
		"tab.unfocusedActiveBorder": colors.crust,
		"tab.unfocusedActiveForeground": colors.text,
		"tab.unfocusedInactiveForeground": colors.surface0,
		"terminal.ansiBlack": colors.crust,
		"terminal.ansiBlue": tokenColors.menu_bg_highlight,
		"terminal.ansiBrightBlack": colors.surface0,
		"terminal.ansiBrightBlue": tokenColors.menu_bg_highlight,
		"terminal.ansiBrightCyan": colors.raspberry,
		"terminal.ansiBrightGreen": tokenColors.menu_bg_highlight,
		"terminal.ansiBrightMagenta": colors.mauve,
		"terminal.ansiBrightRed": tokenColors.button_fg_highlight,
		"terminal.ansiBrightWhite": colors.text,
		"terminal.ansiBrightYellow": colors.lavender,
		"terminal.ansiCyan": colors.raspberry,
		"terminal.ansiGreen": tokenColors.menu_bg_highlight,
		// "terminal.ansiMagenta": colors.color_5,
		"terminal.ansiRed": tokenColors.button_fg_highlight,
		"terminal.ansiWhite": colors.text,
		"terminal.ansiYellow": colors.lavender,
		"terminal.foreground": colors.text,
		"terminalCursor.foreground": colors.text,
		"textBlockQuote.background": colors.surface0,
		"textBlockQuote.border": colors.surface0,
		"textCodeBlock.background": colors.surface0,
		"textLink.activeForeground": opacity(
			tokenColors.menu_bg_highlight,
			0.63,
		),
		"textLink.foreground": tokenColors.menu_bg_highlight,
		"titleBar.activeBackground": colors.crust,
		"titleBar.activeForeground": colors.text,
		"titleBar.border": colors.crust,
		"titleBar.inactiveBackground": colors.crust,
		"titleBar.inactiveForeground": colors.surface0,
		"tree.indentGuidesStroke": colors.surface0,
		"widget.shadow": opacity(colors.crust, 0.44),
	};
}
