import { ThemeContext, WorkbenchColors } from "@/types";
import { mix, opacity, shade, transparent } from "./utils";
import extensions from "./themeExtensions";

export type WorkbenchPartial = Partial<Record<keyof WorkbenchColors, string>>;

// TODO figure out why colors don't look right currently
export function getUiColors(ctx: ThemeContext): WorkbenchPartial {
	const { palette, options } = ctx;
	const { colors, ansiColors, tokenColors, widgetColors } = palette;

	const accent = colors[options.accentColor];
	console.log("Generating UI colors with accent:", accent);
	const dropBackground = opacity(accent, 0.2);
	const border = transparent;

	return {
		// Base colors
		focusBorder: transparent,
		foreground: colors.text,
		disabledForeground: colors.subtext0,
		"widget.shadow": opacity(colors.mantle, 0.5),
		"selection.background": opacity(accent, 0.4),
		descriptionForeground: colors.text,
		errorForeground: colors.cherry,
		"icon.foreground": accent,
		"sash.hoverBorder": accent,

		// Text colors
		"textBlockQuote.background": colors.mantle,
		"textBlockQuote.border": colors.crust,
		"textCodeBlock.background": colors.mantle,
		"textLink.activeForeground": colors.mauve,
		"textLink.foreground": colors.seafoam,
		"textPreformat.foreground": colors.text,
		"textSeparator.foreground": accent,

		// buttons & checkboxes
		"button.background": accent,
		"button.foreground": colors.crust,
		"button.border": transparent,
		"button.separator": transparent,
		"button.hoverBackground": shade(accent, 0.07),
		"button.secondaryForeground": colors.text,
		"button.secondaryBackground": colors.surface1,
		"button.secondaryHoverBackground": shade(colors.surface1, 0.07),
		"checkbox.background": colors.surface1,
		"checkbox.border": transparent,
		"checkbox.foreground": accent,

		"list.highlightForeground": accent,
		"notificationCenter.border": accent,
		"notificationToast.border": accent,
		"notifications.border": accent,
		"panelTitle.activeBorder": accent,
		"pickerGroup.border": accent,
		"pickerGroup.foreground": accent,
		"settings.modifiedItemIndicator": accent,
		"sideBarTitle.foreground": accent,
		"statusBarItem.prominentForeground": accent,
		"progressBar.background": accent,

		"commandCenter.foreground": colors.subtext1,
		"commandCenter.inactiveForeground": colors.subtext1,
		"commandCenter.activeForeground": accent,
		"commandCenter.background": colors.mantle,
		"commandCenter.activeBackground": opacity(colors.surface1, 0.2),
		"commandCenter.border": border,
		"commandCenter.inactiveBorder": border,
		"commandCenter.activeBorder": accent,

		"welcomePage.progress.foreground": accent,
		"symbolIcon.fileForeground": accent,
		"symbolIcon.folderForeground": accent,

		// bracket colors
		"editorBracketHighlight.foreground1": colors.watermelon,
		"editorBracketHighlight.foreground2": colors.mint,
		"editorBracketHighlight.foreground3": colors.champagne,
		"editorBracketHighlight.foreground4": colors.watermelon,
		"editorBracketHighlight.foreground5": colors.mint,
		"editorBracketHighlight.foreground6": colors.champagne,
		"editorBracketHighlight.unexpectedBracket.foreground": colors.cherry,

		// Activity Bar
		"activityBar.activeBorder": colors.watermelon,
		"activityBar.activeFocusBorder": colors.watermelon,
		"activityBar.background": colors.crust,
		"activityBar.foreground": accent,
		"activityBar.border": colors.crust,
		"activityBar.inactiveForeground": colors.surface1,
		"activityBarBadge.background": colors.pink,
		"activityBarBadge.foreground": colors.crust,
		"badge.background": colors.watermelon,
		"badge.foreground": colors.crust,

		// breadcrumbs
		"breadcrumb.activeSelectionForeground": colors.text,
		"breadcrumb.focusForeground": colors.text,
		"breadcrumb.foreground": colors.surface1,
		"breadcrumb.background": colors.base,

		// debug
		"debugToolBar.background": colors.crust,
		"debugToolBar.border": transparent,
		"debugExceptionWidget.background": colors.crust,
		"debugTokenExpression.number": tokenColors.number_value,
		"debugTokenExpression.boolean": colors.peach,
		"debugTokenExpression.string": tokenColors.string_value,
		"debugTokenExpression.error": tokenColors.errorColor,

		// debug icons
		"debugIcon.breakpointForeground": colors.cherry,
		"debugIcon.breakpointDisabledForeground": opacity(colors.cherry, 0.6),
		"debugIcon.breakpointUnverifiedForeground": mix(
			colors.cherry,
			colors.surface1,
			0.5,
		),
		"debugIcon.breakpointCurrentStackframeForeground": colors.surface1,
		"debugIcon.breakpointStackframeForeground": colors.surface1,
		"debugIcon.startForeground": colors.watermelon,
		"debugIcon.pauseForeground": colors.teal,
		"debugIcon.stopForeground": colors.cherry,
		"debugIcon.disconnectForeground": colors.surface1,
		"debugIcon.restartForeground": colors.teal,
		"debugIcon.stepOverForeground": colors.mauve,
		"debugIcon.stepIntoForeground": colors.text,
		"debugIcon.stepOutForeground": colors.text,
		"debugIcon.continueForeground": colors.watermelon,
		"debugIcon.stepBackForeground": colors.surface1,
		"debugConsole.infoForeground": tokenColors.infoColor,
		"debugConsole.warningForeground": colors.peach,
		"debugConsole.errorForeground": colors.cherry,
		"debugConsole.sourceForeground": colors.rosewater,
		"debugConsoleInputIcon.foreground": colors.text,

		// git colors
		"gitDecoration.addedResourceForeground": colors.seafoam,
		"gitDecoration.conflictingResourceForeground": colors.lavender,
		"gitDecoration.deletedResourceForeground": colors.cherry,
		"gitDecoration.ignoredResourceForeground": colors.overlay0,
		"gitDecoration.modifiedResourceForeground": colors.mint,
		"gitDecoration.stageDeletedResourceForeground": colors.cherry,
		"gitDecoration.stageModifiedResourceForeground": colors.champagne,
		"gitDecoration.submoduleResourceForeground": colors.watermelon,
		"gitDecoration.untrackedResourceForeground": colors.mint,
		"editorGhostText.foreground": opacity(colors.surface1, 0.5),

		// git colors -> built-in git graph
		"scmGraph.historyItemRefColor": colors.watermelon,
		"scmGraph.historyItemBaseRefColor": colors.peach,
		"scmGraph.historyItemRemoteRefColor": colors.lavender,
		"scmGraph.foreground1": colors.champagne,
		"scmGraph.foreground2": colors.cherry,
		"scmGraph.foreground3": colors.mint,
		"scmGraph.foreground4": colors.lavender,
		"scmGraph.foreground5": colors.teal,

		"input.background": transparent,
		"input.border": widgetColors.widget_bg,
		"input.foreground": colors.text,
		"input.placeholderForeground": opacity(colors.text, 0.75),
		"inputOption.activeBorder": widgetColors.widget_hl,
		"inputOption.activeBackground": widgetColors.widget_menu_bg,
		"inputOption.activeForeground": colors.text,

		//extensions
		"extensionButton.prominentBackground": accent,
		"extensionButton.prominentHoverBackground": shade(accent, 0.07),

		"diffEditor.insertedTextBackground": opacity(colors.watermelon, 0.1),
		"diffEditor.removedTextBackground": opacity(
			tokenColors.button_fg_highlight,
			0.15,
		),
		"dropdown.background": colors.mantle,
		"dropdown.border": colors.surface1,
		"dropdown.foreground": colors.text,
		"editor.background": colors.mantle,
		"editor.findMatchBackground": opacity(colors.mint, 0.25),
		"editor.findMatchHighlightBackground": opacity(colors.lavender, 0.25),
		"editor.findRangeHighlightBackground": opacity(colors.lavender, 0.25),
		"editor.foreground": colors.text,
		"editor.hoverHighlightBackground": opacity(colors.watermelon, 0.2),
		"editor.lineHighlightBackground": opacity(colors.surface0, 0.25),
		"editor.lineHighlightBorder": opacity(colors.surface0, 0),
		"editor.rangeHighlightBackground": opacity(colors.mauve, 0.25),
		"editor.selectionBackground": opacity(colors.surface0, 0.94),
		"editor.selectionHighlightBackground": opacity(colors.surface0, 0),
		"editor.snippetFinalTabstopHighlightBackground": opacity(
			colors.mauve,
			0.2,
		),
		"editor.snippetFinalTabstopHighlightBorder": colors.mantle,
		"editor.snippetTabstopHighlightBackground": opacity(
			colors.surface1,
			0.6,
		),
		"editor.symbolHighlightBackground": opacity(colors.watermelon, 0.6),
		"editor.wordHighlightBackground": opacity(colors.surface0, 0.75),
		"editor.wordHighlightStrongBackground": opacity(colors.surface0, 0.75),
		"editorBracketMatch.background": colors.surface1,
		"editorBracketMatch.border": transparent,
		"editorCodeLens.foreground": colors.surface1,
		"editorCursor.foreground": colors.text,
		"editorError.foreground": tokenColors.errorColor,
		"editorGroup.border": colors.crust,
		"editorGroup.dropBackground": dropBackground,
		"editorGroupHeader.noTabsBackground": colors.mantle,
		"editorGroupHeader.tabsBackground": colors.mantle,
		"editorGutter.addedBackground": opacity(colors.watermelon, 0.25),
		"editorGutter.background": transparent,
		"editorGutter.deletedBackground": opacity(
			tokenColors.button_fg_highlight,
			0.25,
		),
		"editorGutter.modifiedBackground": opacity(colors.watermelon, 0.25),
		"editorHint.foreground": widgetColors.widget_fg,
		"editorHoverWidget.background": widgetColors.widget_bg,
		"editorHoverWidget.border": widgetColors.widget_bg,
		"editorIndentGuide.activeBackground1": colors.surface1,
		"editorIndentGuide.background1": colors.surface0,
		"editorInfo.foreground": tokenColors.infoColor,
		"editorLightBulb.foreground": colors.raspberry,
		"editorLightBulbAutoFix.foreground": tokenColors.infoColor,
		"editorLineNumber.activeForeground": colors.text,
		"editorLineNumber.foreground": colors.surface1,
		"editorLink.activeForeground": colors.watermelon,
		"editorMarkerNavigation.background": colors.surface1,
		"editorMarkerNavigationError.background":
			tokenColors.button_fg_highlight,
		"editorMarkerNavigationInfo.background": colors.watermelon,
		"editorMarkerNavigationWarning.background": colors.lavender,
		"editorOverviewRuler.addedForeground": opacity(colors.watermelon, 0.5),
		"editorOverviewRuler.border": transparent,
		"editorOverviewRuler.commonContentForeground": colors.surface0,
		"editorOverviewRuler.currentContentForeground": opacity(
			colors.watermelon,
			0.63,
		),
		"editorOverviewRuler.deletedForeground": opacity(
			tokenColors.button_fg_highlight,
			0.5,
		),
		"editorOverviewRuler.errorForeground": tokenColors.errorColor,
		"editorOverviewRuler.findMatchForeground": opacity(
			colors.watermelon,
			0.5,
		),
		"editorOverviewRuler.incomingContentForeground": opacity(
			colors.watermelon,
			0.63,
		),
		"editorOverviewRuler.infoForeground": colors.watermelon,
		"editorOverviewRuler.modifiedForeground": opacity(
			colors.watermelon,
			0.5,
		),
		"editorOverviewRuler.rangeHighlightForeground": opacity(
			colors.watermelon,
			0.5,
		),
		"editorOverviewRuler.selectionHighlightForeground": opacity(
			colors.watermelon,
			0.5,
		),
		"editorOverviewRuler.warningForeground": colors.lavender,
		"editorOverviewRuler.wordHighlightForeground": opacity(
			colors.surface0,
			0.5,
		),
		"editorOverviewRuler.wordHighlightStrongForeground": opacity(
			colors.surface0,
			0.375,
		),
		"editorRuler.foreground": colors.surface1,
		"editorSuggestWidget.background": widgetColors.widget_bg,
		"editorSuggestWidget.border": widgetColors.widget_bg,
		"editorSuggestWidget.foreground": widgetColors.widget_fg,
		"editorSuggestWidget.highlightForeground": widgetColors.widget_fg,
		"editorSuggestWidget.selectedBackground": widgetColors.widget_hl,
		"editorUnnecessaryCode.border": colors.surface0,
		"editorUnnecessaryCode.opacity": colors.text,
		"editorWarning.foreground": tokenColors.warnColor,
		"editorWhitespace.foreground": colors.surface0,
		"editorWidget.background": widgetColors.widget_menu_bg,
		"editorWidget.border": widgetColors.widget_bg,
		"extensionBadge.remoteBackground": colors.watermelon,
		"extensionBadge.remoteForeground": colors.mantle,
		"extensionButton.prominentForeground": colors.mantle,

		"inputValidation.errorBackground": colors.mantle,
		"inputValidation.errorBorder": tokenColors.errorColor,
		"inputValidation.errorForeground": colors.cherry,
		"inputValidation.infoBackground": colors.mantle,
		"inputValidation.infoBorder": tokenColors.infoColor,
		"inputValidation.infoForeground": colors.mauve,
		"inputValidation.warningBackground": colors.mantle,
		"inputValidation.warningBorder": tokenColors.warnColor,
		"inputValidation.warningForeground": colors.peach,

		"list.activeSelectionBackground": opacity(colors.mantle, 0.88),
		"list.activeSelectionForeground": colors.text,
		"list.dropBackground": dropBackground,
		"list.errorForeground": tokenColors.button_fg_highlight,
		"list.focusBackground": opacity(colors.surface1, 0.5),
		"list.focusForeground": colors.text,
		"list.hoverBackground": opacity(colors.crust, 0),
		"list.hoverForeground": colors.text,
		"list.inactiveFocusBackground": opacity(colors.surface1, 0.42),
		"list.inactiveSelectionBackground": opacity(colors.mantle, 0.79),
		"list.inactiveSelectionForeground": colors.surface0,
		"list.invalidItemForeground": opacity(
			tokenColors.button_fg_highlight,
			0.5,
		),
		"list.warningForeground": colors.lavender,
		"menu.background": colors.crust,
		"menu.foreground": colors.text,
		"menu.selectionBackground": colors.mantle,
		"menu.selectionForeground": colors.text,
		"menubar.selectionBackground": colors.mantle,
		"menubar.selectionBorder": colors.mantle,
		"merge.border": opacity(colors.mantle, 0),
		"merge.currentContentBackground": opacity(colors.watermelon, 0.1),
		"merge.currentHeaderBackground": opacity(colors.watermelon, 0.19),
		"merge.incomingContentBackground": opacity(colors.watermelon, 0.1),
		"merge.incomingHeaderBackground": opacity(colors.watermelon, 0.19),

		// minimap
		"minimap.errorHighlight": opacity(
			tokenColors.button_fg_highlight,
			0.44,
		),
		"minimap.findMatchHighlight": opacity(colors.watermelon, 0.25),
		"minimap.selectionHighlight": opacity(colors.surface1, 0.94),
		"minimap.warningHighlight": opacity(colors.lavender, 0.8),
		"minimap.background": opacity(colors.base, 0.5),
		"minimapGutter.addedBackground": opacity(colors.watermelon, 0.63),
		"minimapGutter.deletedBackground": opacity(
			tokenColors.button_fg_highlight,
			0.63,
		),
		"minimapGutter.modifiedBackground": opacity(colors.watermelon, 0.63),

		"notificationCenterHeader.background": colors.surface0,
		"notificationCenterHeader.foreground": colors.text,
		"notificationLink.foreground": colors.watermelon,
		"notifications.background": colors.mantle,
		"notifications.foreground": colors.text,
		"notificationsErrorIcon.foreground": accent,
		"notificationsInfoIcon.foreground": accent,
		"notificationsWarningIcon.foreground": accent,

		"panelInput.border": widgetColors.widget_bg,
		"panelTitle.activeForeground": colors.subtext0,
		"panelTitle.inactiveForeground": colors.surface0,
		"peekView.border": widgetColors.widget_bg,
		"peekViewEditor.background": widgetColors.widget_bg,
		"peekViewEditor.matchHighlightBackground": widgetColors.widget_hl,
		"peekViewEditorGutter.background": widgetColors.widget_menu_bg,
		"peekViewResult.background": widgetColors.widget_menu_bg,
		"peekViewResult.fileForeground": widgetColors.widget_fg,
		"peekViewResult.matchHighlightBackground": widgetColors.widget_hl,
		"peekViewResult.selectionBackground": widgetColors.widget_menu_bg,
		"peekViewTitle.background": widgetColors.widget_menu_bg,
		"peekViewTitleDescription.foreground": widgetColors.widget_fg,
		"peekViewTitleLabel.foreground": widgetColors.widget_fg,
		"problemsErrorIcon.foreground": tokenColors.errorColor,
		"problemsInfoIcon.foreground": tokenColors.infoColor,
		"problemsWarningIcon.foreground": tokenColors.warnColor,

		// Command Palette / Quick Input
		"quickInput.foreground": colors.text,
		"quickInputList.focusBackground": colors.surface0,
		"quickInput.background": colors.subSurface,
		"keybindingLabel.background": colors.subSurface,
		"keybindingLabel.foreground": colors.text,

		"scrollbar.shadow": colors.mantle,
		"scrollbarSlider.activeBackground": opacity(colors.surface0, 0.69),
		"scrollbarSlider.background": opacity(colors.surface0, 0.44),
		"scrollbarSlider.hoverBackground": opacity(colors.surface0, 0.56),

		"settings.checkboxBackground": colors.mantle,
		"settings.checkboxBorder": colors.surface1,
		"settings.checkboxForeground": colors.raspberry,
		"settings.dropdownBackground": colors.mantle,
		"settings.dropdownBorder": colors.surface1,
		"settings.dropdownForeground": colors.watermelon,
		"settings.headerForeground": colors.text,
		"settings.numberInputBackground": colors.mantle,
		"settings.numberInputBorder": widgetColors.widget_bg,
		"settings.numberInputForeground": colors.mauve,
		"settings.textInputBackground": widgetColors.widget_bg,
		"settings.textInputBorder": widgetColors.widget_bg,
		"settings.textInputForeground": colors.watermelon,

		"sideBar.background": colors.crust,
		"sideBar.foreground": colors.overlay0,
		"sideBarSectionHeader.background": colors.mantle,
		"sideBarSectionHeader.foreground": colors.surface1,

		// status bar
		"statusBarItem.errorBackground": tokenColors.errorColor,
		"statusBarItem.errorForeground": colors.mantle,
		"statusBar.background": colors.rosewater,
		"statusBar.border": colors.mantle,
		"statusBar.debuggingBackground": tokenColors.button_bg_highlight,
		"statusBar.debuggingBorder": tokenColors.button_fg_highlight,
		"statusBar.debuggingForeground": colors.mantle,
		"statusBar.foreground": colors.mantle,
		"statusBar.noFolderBackground": colors.mantle,
		"statusBar.noFolderBorder": colors.crust,
		"statusBar.noFolderForeground": colors.mantle,
		"statusBarItem.activeBackground": opacity(colors.surface1, 0.63),
		"statusBarItem.hoverBackground": colors.watermelon,
		"statusBarItem.remoteBackground": tokenColors.button_bg_highlight,
		"statusBarItem.remoteForeground": colors.mantle,

		// symbols in outline, autocomplete, etc.
		"symbolIcon.arrayForeground": colors.text,
		"symbolIcon.booleanForeground": colors.mauve,
		"symbolIcon.classForeground": tokenColors.class_name,
		"symbolIcon.colorForeground": colors.text,
		"symbolIcon.constantForeground": colors.mauve,
		"symbolIcon.constructorForeground": colors.watermelon,
		"symbolIcon.enumeratorForeground": colors.mauve,
		"symbolIcon.enumeratorMemberForeground": colors.mauve,
		"symbolIcon.eventForeground": colors.watermelon,
		"symbolIcon.fieldForeground": tokenColors.field_name,
		"symbolIcon.functionForeground": tokenColors.method,
		"symbolIcon.interfaceForeground": colors.watermelon,
		"symbolIcon.keyForeground": colors.watermelon,
		"symbolIcon.keywordForeground": tokenColors.button_fg_highlight,
		"symbolIcon.methodForeground": tokenColors.method,
		"symbolIcon.moduleForeground": tokenColors.button_fg_highlight,
		"symbolIcon.namespaceForeground": tokenColors.button_fg_highlight,
		"symbolIcon.nullForeground": colors.mauve,
		"symbolIcon.numberForeground": colors.mauve,
		"symbolIcon.objectForeground": colors.watermelon,
		"symbolIcon.operatorForeground": tokenColors.button_fg_highlight,
		"symbolIcon.packageForeground": tokenColors.button_fg_highlight,
		"symbolIcon.propertyForeground": tokenColors.property,
		"symbolIcon.referenceForeground": colors.watermelon,
		"symbolIcon.snippetForeground": colors.text,
		"symbolIcon.stringForeground": colors.lavender,
		"symbolIcon.structForeground": colors.watermelon,
		"symbolIcon.textForeground": colors.text,
		"symbolIcon.typeParameterForeground": colors.raspberry,
		"symbolIcon.unitForeground": colors.text,
		"symbolIcon.variableForeground": tokenColors.class_name,

		// tabs
		"tab.activeBackground": colors.mantle,
		"tab.activeBorder": accent,
		"tab.border": colors.base,
		"tab.hoverBackground": colors.mantle,
		"tab.inactiveBackground": colors.mantle,
		"tab.inactiveForeground": colors.surface1,
		"tab.unfocusedActiveBorder": colors.crust,
		"tab.unfocusedActiveForeground": colors.text,
		"tab.unfocusedInactiveForeground": colors.surface0,
		"tab.activeBorderTop": colors.mantle,
		"tab.activeForeground": accent,
		"tab.hoverForeground": accent,
		"tab.lastPinnedBorder": accent,
		"tab.unfocusedActiveBorderTop": opacity(accent, 0.3),

		// terminal / panel
		"panel.background": colors.subSurface,
		"panel.border": colors.surface0,
		"terminal.tab.activeBorder": accent,
		"terminal.ansiBlack": ansiColors.black,
		"terminal.ansiBrightBlack": ansiColors.brightBlack,
		"terminal.ansiRed": ansiColors.red,
		"terminal.ansiBrightRed": ansiColors.brightRed,
		"terminal.ansiGreen": ansiColors.green,
		"terminal.ansiBrightGreen": ansiColors.brightGreen,
		"terminal.ansiYellow": ansiColors.yellow,
		"terminal.ansiBrightYellow": ansiColors.brightYellow,
		"terminal.ansiBlue": ansiColors.blue,
		"terminal.ansiBrightBlue": ansiColors.brightBlue,
		"terminal.ansiCyan": ansiColors.cyan,
		"terminal.ansiBrightCyan": ansiColors.brightCyan,
		"terminal.ansiMagenta": ansiColors.magenta,
		"terminal.ansiBrightMagenta": ansiColors.brightMagenta,
		"terminal.ansiWhite": ansiColors.white,
		"terminal.ansiBrightWhite": ansiColors.brightWhite,
		"terminal.foreground": colors.text,
		"terminalCursor.foreground": colors.text,
		"terminalCommandDecoration.defaultBackground": colors.subSurface,
		"terminalCommandDecoration.errorBackground": tokenColors.errorColor,
		"terminalCommandDecoration.successBackground": colors.seafoam,

		// title bar
		"titleBar.activeBackground": colors.crust,
		"titleBar.activeForeground": colors.text,
		"titleBar.border": colors.crust,
		"titleBar.inactiveBackground": colors.crust,
		"titleBar.inactiveForeground": colors.surface1,

		"tree.indentGuidesStroke": colors.surface1,

		"inlineChat.foreground": colors.subtext0,
		"chat.slashCommandBackground": colors.subSurface,
		"chat.slashCommandForeground": colors.seafoam,
		"editorStickyScrollHover.background": colors.subSurface,
		...extensions(ctx),
	};
}
