import { colors, tokenColors, gruvvyWatermelonColors, workBenchColors } from "./colors.js";

const bench = {
    "editorBracketHighlight.foreground1": tokenColors.buttonHighlight,
    "editorBracketHighlight.foreground2": colors.color_3,
    "editorBracketHighlight.foreground3": tokenColors.menuHighlight,
    "editorBracketHighlight.foreground4": colors.color_2,
    "activityBar.activeBorder": tokenColors.menuHighlight,
    "activityBar.activeFocusBorder": tokenColors.menuHighlight,
    "activityBar.background": colors.dark_hard,
    "activityBar.border": colors.dark_hard,
    "activityBar.foreground": colors.light_hard,
    "activityBar.inactiveForeground": colors.light_0,
    "activityBarBadge.background": colors.color_2,
    "activityBarBadge.foreground": gruvvyWatermelonColors.black,
    "badge.background": gruvvyWatermelonColors.bright_blue,
    "badge.foreground": gruvvyWatermelonColors.black,
    "breadcrumb.activeSelectionForeground": colors.light_hard,
    "breadcrumb.focusForeground": colors.light_hard,
    "breadcrumb.foreground": colors.light_0,
    "button.background": colors.color_2,
    "button.foreground": colors.dark_normal,
    "button.hoverBackground": tokenColors.menuHighlight,
    "checkbox.background": colors.dark_normal,
    "checkbox.border": colors.dark_1,
    "checkbox.foreground": colors.color_3,
    "debugToolBar.background": colors.dark_normal,
    "diffEditor.insertedTextBackground": tokenColors.menuHighlight + "20",
    "diffEditor.removedTextBackground": tokenColors.buttonHighlight + "26",
    "dropdown.background": colors.dark_normal,
    "dropdown.border": colors.dark_1,
    "dropdown.foreground": colors.light_hard,
    "editor.background": colors.dark_normal,
    "editor.findMatchBackground": gruvvyWatermelonColors.bright_aqua + "40",
    "editor.findMatchHighlightBackground":
        gruvvyWatermelonColors.bright_purple + "40",
    "editor.findRangeHighlightBackground":
        gruvvyWatermelonColors.bright_purple + "40",
    "editor.foreground": colors.light_hard,
    "editor.hoverHighlightBackground": tokenColors.menuHighlight + "36",
    "editor.lineHighlightBackground": colors.dark_0 + "40",
    "editor.lineHighlightBorder": colors.dark_0 + "00",
    "editor.rangeHighlightBackground": colors.color_5 + "40",
    "editor.selectionBackground": colors.dark_0 + "f0",
    "editor.selectionHighlightBackground": colors.dark_0 + "00",
    "editor.snippetFinalTabstopHighlightBackground": colors.color_5 + "30",
    "editor.snippetFinalTabstopHighlightBorder": colors.dark_normal,
    "editor.snippetTabstopHighlightBackground": colors.dark_1 + "a0",
    "editor.symbolHighlightBackground": tokenColors.menuHighlight + "38",
    "editor.wordHighlightBackground": colors.dark_0 + "c0",
    "editor.wordHighlightStrongBackground": colors.dark_0 + "c0",
    "editorBracketMatch.background": colors.dark_1,
    "editorBracketMatch.border": colors.dark_normal + "00",
    "editorCodeLens.foreground": colors.light_0,
    "editorCursor.foreground": colors.light_hard,
    "editorError.foreground": tokenColors.errorColor,
    "editorGroup.border": colors.dark_hard,
    "editorGroup.dropBackground": colors.dark_1 + "60",
    "editorGroupHeader.noTabsBackground": colors.dark_normal,
    "editorGroupHeader.tabsBackground": colors.dark_normal,
    "editorGutter.addedBackground": tokenColors.menuHighlight + "40",
    "editorGutter.background": colors.dark_normal + "00",
    "editorGutter.deletedBackground": tokenColors.buttonHighlight + "40",
    "editorGutter.modifiedBackground": tokenColors.menuHighlight + "40",
    "editorHint.foreground": workBenchColors.widget_fg,
    "editorHoverWidget.background": workBenchColors.widget_bg,
    "editorHoverWidget.border": workBenchColors.widget_bg,
    "editorIndentGuide.activeBackground1": colors.dark_1,
    "editorIndentGuide.background1": colors.dark_0,
    "editorInfo.foreground": tokenColors.menuHighlight,
    "editorLightBulb.foreground": gruvvyWatermelonColors.purple_pink,
    "editorLightBulbAutoFix.foreground": tokenColors.menuHighlight,
    "editorLineNumber.activeForeground": colors.light_hard,
    "editorLineNumber.foreground": colors.light_0,
    "editorLink.activeForeground": tokenColors.menuHighlight,
    "editorMarkerNavigation.background": colors.dark_1,
    "editorMarkerNavigationError.background": tokenColors.buttonHighlight,
    "editorMarkerNavigationInfo.background": tokenColors.menuHighlight,
    "editorMarkerNavigationWarning.background": colors.color_4,
    "editorOverviewRuler.addedForeground": tokenColors.menuHighlight + "80",
    "editorOverviewRuler.border": colors.dark_normal + "00",
    "editorOverviewRuler.commonContentForeground": colors.light_0,
    "editorOverviewRuler.currentContentForeground":
        tokenColors.menuHighlight + "a0",
    "editorOverviewRuler.deletedForeground":
        tokenColors.buttonHighlight + "80",
    "editorOverviewRuler.errorForeground": tokenColors.errorColor,
    "editorOverviewRuler.findMatchForeground":
        tokenColors.menuHighlight + "80",
    "editorOverviewRuler.incomingContentForeground":
        tokenColors.menuHighlight + "a0",
    "editorOverviewRuler.infoForeground": tokenColors.menuHighlight,
    "editorOverviewRuler.modifiedForeground":
        tokenColors.menuHighlight + "80",
    "editorOverviewRuler.rangeHighlightForeground":
        tokenColors.menuHighlight + "80",
    "editorOverviewRuler.selectionHighlightForeground":
        tokenColors.menuHighlight + "80",
    "editorOverviewRuler.warningForeground": colors.color_4,
    "editorOverviewRuler.wordHighlightForeground": colors.light_0 + "80",
    "editorOverviewRuler.wordHighlightStrongForeground":
        colors.light_0 + "60",
    "editorRuler.foreground": colors.dark_1,
    "editorSuggestWidget.background": workBenchColors.widget_bg,
    "editorSuggestWidget.border": workBenchColors.widget_bg,
    "editorSuggestWidget.foreground": workBenchColors.widget_fg,
    "editorSuggestWidget.highlightForeground": workBenchColors.widget_fg,
    "editorSuggestWidget.selectedBackground": workBenchColors.widget_hl,
    "editorUnnecessaryCode.border": colors.light_0,
    "editorUnnecessaryCode.opacity": colors.light_hard,
    "editorWarning.foreground": tokenColors.warnColor,
    "editorWhitespace.foreground": colors.light_0,
    "editorWidget.background": workBenchColors.widget_menu_bg,
    "editorWidget.border": workBenchColors.widget_bg,
    errorForeground: tokenColors.buttonHighlight,
    "extensionBadge.remoteBackground": tokenColors.menuHighlight,
    "extensionBadge.remoteForeground": colors.dark_normal,
    "extensionButton.prominentBackground": tokenColors.menuHighlight,
    "extensionButton.prominentForeground": colors.dark_normal,
    "extensionButton.prominentHoverBackground": tokenColors.menuHighlight,
    focusBorder: colors.dark_1 + "00",
    foreground: colors.light_hard,
    "gitDecoration.addedResourceForeground": tokenColors.menuHighlight + "80",
    "gitDecoration.conflictingResourceForeground": colors.color_5 + "90",
    "gitDecoration.deletedResourceForeground": colors.color_3,
    "gitDecoration.ignoredResourceForeground": colors.dark_1,
    "gitDecoration.modifiedResourceForeground":
        tokenColors.menuHighlight + "d1",
    "gitDecoration.submoduleResourceForeground": colors.color_3 + "d1",
    "gitDecoration.untrackedResourceForeground": colors.color_4 + "d1",
    "icon.foreground": tokenColors.menuHighlight,
    "input.background": colors.dark_normal + "00",
    "input.border": workBenchColors.widget_bg,
    "input.foreground": colors.light_hard,
    "input.placeholderForeground": colors.light_0,
    "inputOption.activeBorder": workBenchColors.widget_hl,
    "inputValidation.errorBackground": colors.dark_0,
    "inputValidation.errorBorder": tokenColors.buttonHighlight,
    "inputValidation.errorForeground": tokenColors.buttonHighlight,
    "inputValidation.infoBackground": colors.dark_0,
    "inputValidation.infoBorder": workBenchColors.widget_bg,
    "inputValidation.infoForeground": tokenColors.menuHighlight,
    "inputValidation.warningBackground": colors.dark_0,
    "inputValidation.warningBorder": colors.color_4,
    "inputValidation.warningForeground": colors.color_4,
    "list.activeSelectionBackground": colors.dark_normal + "e0",
    "list.activeSelectionForeground": colors.light_hard,
    "list.dropBackground": colors.dark_0 + "80",
    "list.errorForeground": tokenColors.buttonHighlight,
    "list.focusBackground": colors.dark_1 + "80",
    "list.focusForeground": colors.light_hard,
    "list.highlightForeground": tokenColors.menuHighlight,
    "list.hoverBackground": colors.dark_hard + "00",
    "list.hoverForeground": colors.light_hard,
    "list.inactiveFocusBackground": colors.dark_1 + "68",
    "list.inactiveSelectionBackground": colors.dark_normal + "c8",
    "list.inactiveSelectionForeground": colors.light_0,
    "list.invalidItemForeground": tokenColors.buttonHighlight + "80",
    "list.warningForeground": colors.color_4,
    "menu.background": colors.dark_hard,
    "menu.foreground": colors.light_hard,
    "menu.selectionBackground": colors.dark_normal,
    "menu.selectionForeground": colors.light_hard,
    "menubar.selectionBackground": colors.dark_normal,
    "menubar.selectionBorder": colors.dark_normal,
    "merge.border": colors.dark_normal + "00",
    "merge.currentContentBackground": tokenColors.menuHighlight + "1a",
    "merge.currentHeaderBackground": tokenColors.menuHighlight + "30",
    "merge.incomingContentBackground": tokenColors.menuHighlight + "1a",
    "merge.incomingHeaderBackground": tokenColors.menuHighlight + "30",
    "minimap.errorHighlight": tokenColors.buttonHighlight + "70",
    "minimap.findMatchHighlight": tokenColors.menuHighlight + "40",
    "minimap.selectionHighlight": colors.dark_1 + "f0",
    "minimap.warningHighlight": colors.color_4 + "50",
    "minimapGutter.addedBackground": tokenColors.menuHighlight + "a0",
    "minimapGutter.deletedBackground": tokenColors.buttonHighlight + "a0",
    "minimapGutter.modifiedBackground": tokenColors.menuHighlight + "a0",
    "notificationCenterHeader.background": colors.dark_0,
    "notificationCenterHeader.foreground": colors.light_hard,
    "notificationLink.foreground": tokenColors.menuHighlight,
    "notifications.background": colors.dark_normal,
    "notifications.foreground": colors.light_hard,
    "notificationsErrorIcon.foreground": tokenColors.buttonHighlight,
    "notificationsInfoIcon.foreground": tokenColors.menuHighlight,
    "notificationsWarningIcon.foreground": colors.color_4,
    "panel.background": colors.dark_0,
    "panel.border": colors.dark_0,
    "panelInput.border": workBenchColors.widget_bg,
    "panelTitle.activeBorder": tokenColors.menuHighlight,
    "panelTitle.activeForeground": colors.light_soft,
    "panelTitle.inactiveForeground": colors.light_0,
    "peekView.border": workBenchColors.widget_bg,
    "peekViewEditor.background": workBenchColors.widget_bg,
    "peekViewEditor.matchHighlightBackground": workBenchColors.widget_hl,
    "peekViewEditorGutter.background": workBenchColors.widget_menu_bg,
    "peekViewResult.background": workBenchColors.widget_menu_bg,
    "peekViewResult.fileForeground": workBenchColors.widget_fg,
    "peekViewResult.matchHighlightBackground": workBenchColors.widget_hl,
    "peekViewResult.selectionBackground": workBenchColors.widget_menu_bg,
    "peekViewTitle.background": workBenchColors.widget_menu_bg,
    "peekViewTitleDescription.foreground": workBenchColors.widget_fg,
    "peekViewTitleLabel.foreground": workBenchColors.widget_fg,
    "pickerGroup.border": colors.light_hard + "1a",
    "problemsErrorIcon.foreground": tokenColors.buttonHighlight,
    "problemsInfoIcon.foreground": tokenColors.menuHighlight,
    "problemsWarningIcon.foreground": colors.color_4,
    "progressBar.background": tokenColors.menuHighlight,
    "quickInputList.focusBackground": workBenchColors.widget_hl,
    "scrollbar.shadow": colors.dark_hard + "70",
    "scrollbarSlider.activeBackground": colors.light_0 + "b0",
    "scrollbarSlider.background": colors.light_0 + "70",
    "scrollbarSlider.hoverBackground": colors.light_0 + "90",
    "selection.background": colors.dark_1 + "e0",
    "settings.checkboxBackground": colors.dark_normal,
    "settings.checkboxBorder": colors.dark_1,
    "settings.checkboxForeground": colors.color_3,
    "settings.dropdownBackground": colors.dark_normal,
    "settings.dropdownBorder": colors.dark_1,
    "settings.dropdownForeground": tokenColors.menuHighlight,
    "settings.headerForeground": colors.light_hard,
    "settings.numberInputBackground": colors.dark_normal,
    "settings.numberInputBorder": workBenchColors.widget_bg,
    "settings.numberInputForeground": colors.color_5,
    "settings.textInputBackground": workBenchColors.widget_bg,
    "settings.textInputBorder": workBenchColors.widget_bg,
    "settings.textInputForeground": tokenColors.menuHighlight,
    "sideBar.background": colors.dark_hard,
    "sideBar.foreground": colors.light_0,
    "sideBarSectionHeader.background": colors.dark_normal + "00",
    "sideBarSectionHeader.foreground": colors.light_0,
    "sideBarTitle.foreground": colors.light_0,
    "statusBar.background": gruvvyWatermelonColors.bright_red_pink,
    "statusBar.border": colors.dark_hard,
    "statusBar.debuggingBackground": tokenColors.buttonHighlight,
    "statusBar.debuggingBorder": tokenColors.buttonHighlight,
    "statusBar.debuggingForeground": colors.dark_normal,
    "statusBar.foreground": colors.dark_normal,
    "statusBar.noFolderBackground": colors.color_2,
    "statusBar.noFolderBorder": colors.dark_hard,
    "statusBar.noFolderForeground": colors.dark_normal,
    "statusBarItem.activeBackground": colors.dark_1 + "a0",
    "statusBarItem.hoverBackground": tokenColors.menuHighlight,
    "statusBarItem.remoteBackground": tokenColors.buttonHighlight,
    "statusBarItem.remoteForeground": colors.dark_normal,
    "symbolIcon.arrayForeground": colors.light_hard,
    "symbolIcon.booleanForeground": colors.color_5,
    "symbolIcon.classForeground": tokenColors.class_name,
    "symbolIcon.colorForeground": colors.light_hard,
    "symbolIcon.constantForeground": colors.color_5,
    "symbolIcon.constructorForeground": tokenColors.menuHighlight,
    "symbolIcon.enumeratorForeground": colors.color_5,
    "symbolIcon.enumeratorMemberForeground": colors.color_5,
    "symbolIcon.eventForeground": tokenColors.menuHighlight,
    "symbolIcon.fieldForeground": tokenColors.field_name,
    "symbolIcon.fileForeground": colors.light_hard,
    "symbolIcon.folderForeground": colors.light_hard,
    "symbolIcon.functionForeground": tokenColors.method,
    "symbolIcon.interfaceForeground": tokenColors.menuHighlight,
    "symbolIcon.keyForeground": tokenColors.menuHighlight,
    "symbolIcon.keywordForeground": tokenColors.buttonHighlight,
    "symbolIcon.methodForeground": tokenColors.method,
    "symbolIcon.moduleForeground": tokenColors.buttonHighlight,
    "symbolIcon.namespaceForeground": tokenColors.buttonHighlight,
    "symbolIcon.nullForeground": colors.color_5,
    "symbolIcon.numberForeground": colors.color_5,
    "symbolIcon.objectForeground": tokenColors.menuHighlight,
    "symbolIcon.operatorForeground": tokenColors.buttonHighlight,
    "symbolIcon.packageForeground": tokenColors.buttonHighlight,
    "symbolIcon.propertyForeground": tokenColors.property,
    "symbolIcon.referenceForeground": tokenColors.menuHighlight,
    "symbolIcon.snippetForeground": colors.light_hard,
    "symbolIcon.stringForeground": colors.color_4,
    "symbolIcon.structForeground": tokenColors.menuHighlight,
    "symbolIcon.textForeground": colors.light_hard,
    "symbolIcon.typeParameterForeground": colors.color_3,
    "symbolIcon.unitForeground": colors.light_hard,
    "symbolIcon.variableForeground": tokenColors.class_name,
    "tab.activeBackground": colors.dark_normal,
    "tab.activeBorder": tokenColors.hintColor,
    "tab.activeForeground": colors.light_hard,
    "tab.border": colors.dark_hard,
    "tab.hoverBackground": colors.dark_normal,
    "tab.inactiveBackground": colors.dark_normal,
    "tab.inactiveForeground": colors.light_0,
    "tab.unfocusedActiveBorder": colors.dark_hard,
    "tab.unfocusedActiveForeground": colors.light_hard,
    "tab.unfocusedInactiveForeground": colors.light_0,
    "terminal.ansiBlack": colors.dark_hard,
    "terminal.ansiBlue": tokenColors.menuHighlight,
    "terminal.ansiBrightBlack": colors.dark_0,
    "terminal.ansiBrightBlue": tokenColors.menuHighlight,
    "terminal.ansiBrightCyan": colors.color_3,
    "terminal.ansiBrightGreen": tokenColors.menuHighlight,
    "terminal.ansiBrightMagenta": colors.color_5,
    "terminal.ansiBrightRed": tokenColors.buttonHighlight,
    "terminal.ansiBrightWhite": colors.light_hard,
    "terminal.ansiBrightYellow": colors.color_4,
    "terminal.ansiCyan": colors.color_3,
    "terminal.ansiGreen": tokenColors.menuHighlight,
    // "terminal.ansiMagenta": colors.color_5,
    "terminal.ansiRed": tokenColors.buttonHighlight,
    "terminal.ansiWhite": colors.light_hard,
    "terminal.ansiYellow": colors.color_4,
    "terminal.foreground": colors.light_hard,
    "terminalCursor.foreground": colors.light_hard,
    "textBlockQuote.background": colors.dark_0,
    "textBlockQuote.border": colors.light_0,
    "textCodeBlock.background": colors.dark_0,
    "textLink.activeForeground": tokenColors.menuHighlight + "a0",
    "textLink.foreground": tokenColors.menuHighlight,
    "titleBar.activeBackground": colors.dark_hard,
    "titleBar.activeForeground": colors.light_hard,
    "titleBar.border": colors.dark_hard,
    "titleBar.inactiveBackground": colors.dark_hard,
    "titleBar.inactiveForeground": colors.light_0,
    "tree.indentGuidesStroke": colors.light_0,
    "widget.shadow": colors.dark_hard + "70",
    "activityBar.activeBorder": tokenColors.menuHighlight,
}

export { bench };